/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;

public class App {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(args[0]);
        System.out.println(new App().getGreeting());
        if(args.length != 3){
            //three arguments
            System.out.println("three arguments required");
        }
//        System.out.println(readFile("src/main/resources/" + args[0]));
//        System.out.println(grayscale(readFile("src/main/resources/" + args[0])));
//        System.out.println(saveFile(grayscale(readFile("src/main/resources/" + args[0]))));
        readFile("src/main/resources/" + args[0]);
    }


    //read a file function

    public static void readFile(String input){
        BufferedImage image;
        try {
            File bmpFile = new File(input);
            image = ImageIO.read(bmpFile);
            System.out.println(image);

            saveFile(grayscale(image));

        }
        catch(IOException e) {

        }
    }

    //run color transformation
    public static BufferedImage grayscale(BufferedImage img) {

        for (int x = 0; x < img.getWidth(); x++) {
            for (int y = 0; y < img.getHeight(); y++) {
                int color = img.getRGB(x, y);
                Color c = new Color(color);
                int average = (c.getRed() + c.getBlue() + c.getGreen()) / 3;
                Color gray = new Color(average, average, average);
                img.setRGB(x, y, gray.getRGB());
            }
        }
        return img;
    }


    //write it out to a new file
    public static void saveFile(final BufferedImage img){
        try {
            File f;
            f = new File("src/main/resources/boygray");
            ImageIO.write(img, "bmp", f);
        }
        catch(IOException e) {
            System.out.println("File not found");
            System.out.println(e);
        }
    }

}
